# Generated by Django 2.2 on 2020-08-10 22:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0002_auto_20200807_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPromocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(blank=True, max_length=10, null=True)),
                ('discount_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('maximum_discount_price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.TextField(blank=True, choices=[('Grocery', 'Grocery'), ('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Food', 'Food')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_shop_promocode_shop', to='Shop.Shop')),
            ],
            options={
                'verbose_name': 'Shop Promocode',
                'verbose_name_plural': 'Shop Promocodes',
            },
        ),
    ]
