# Generated by Django 2.2 on 2020-10-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Promocode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppromocode',
            name='category',
            field=models.TextField(blank=True, choices=[('Grocery', 'Grocery'), ('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Food', 'Food'), ('FoodPackage', 'FoodPackage')], null=True),
        ),
    ]
