# Generated by Django 2.2 on 2020-07-28 23:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_auto_20200728_2317'),
        ('Client', '0002_clientfruitcart_clientvegetablecart_shopfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGroceryCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_grocery_cart_client', to='Client.Client')),
                ('grocery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_grocery_cart_grocery', to='Shop.Grocery')),
                ('grocery_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_grocery_cart_grocery_price', to='Shop.GroceryPrice')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_grocery_cart_shop', to='Shop.Shop')),
            ],
            options={
                'verbose_name': 'Client Grocery Cart',
                'verbose_name_plural': 'Client Grocery Carts',
            },
        ),
        migrations.CreateModel(
            name='ClientFoodMealCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_food_meal_cart_client', to='Client.Client')),
                ('food_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_food_meal_cart_grocery', to='Shop.FoodMeal')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_client_food_meal_cart_shop', to='Shop.Shop')),
            ],
            options={
                'verbose_name': 'Client Food Meal Cart',
                'verbose_name_plural': 'Client Food Meal Carts',
            },
        ),
    ]
