# Generated by Django 2.2 on 2020-09-30 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20200807_0244'),
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSlotsAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_driver_slot_driver', to='Driver.Driver')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_driver_slot_slot', to='Shop.Slots')),
            ],
            options={
                'verbose_name': 'Driver Slot Assigned',
                'verbose_name_plural': 'Driver Slots Assigned',
            },
        ),
    ]
