# Generated by Django 2.2 on 2020-08-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vegetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetableprice',
            name='price_type',
            field=models.TextField(blank=True, choices=[('Kg', 'Kg')], null=True),
        ),
    ]
