# Generated by Django 2.2 on 2020-08-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodPackage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpackage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodpackage',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
