# Generated by Django 2.2 on 2020-09-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodPackage', '0002_auto_20200809_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpackage',
            name='food_type',
            field=models.TextField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], null=True),
        ),
    ]
