# Generated by Django 2.2 on 2020-08-07 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Food', '0001_initial'),
        ('Fruit', '0001_initial'),
        ('Grocery', '0001_initial'),
        ('Vegetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.TextField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], null=True)),
                ('vegetable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vegetable_vegetable_approval_vegetable', to='Vegetable.Vegetable')),
            ],
            options={
                'verbose_name': 'Vegetable Approval',
                'verbose_name_plural': 'Vegetable Approvals',
            },
        ),
        migrations.CreateModel(
            name='GroceryApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.TextField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], null=True)),
                ('grocery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_grocery_approval_grocery', to='Grocery.Grocery')),
            ],
            options={
                'verbose_name': 'Grocery Approval',
                'verbose_name_plural': 'Grocery Approvals',
            },
        ),
        migrations.CreateModel(
            name='FruitApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.TextField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], null=True)),
                ('fruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruit_fruit_approval_fruit', to='Fruit.Fruit')),
            ],
            options={
                'verbose_name': 'Fruit Approval',
                'verbose_name_plural': 'Fruit Approvals',
            },
        ),
        migrations.CreateModel(
            name='FoodMealApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.TextField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], null=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_food_meal_meal', to='Food.FoodMeal')),
            ],
            options={
                'verbose_name': 'Food Meal Approval',
                'verbose_name_plural': 'Food Meal Approvals',
            },
        ),
    ]
