# Generated by Django 2.2 on 2020-07-02 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shop', '0008_grocery_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('grocery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_grocery_approval_grocery', to='Shop.Grocery')),
            ],
            options={
                'verbose_name': 'Grocery Approval',
                'verbose_name_plural': 'Grocery Approvals',
            },
        ),
    ]
