# Generated by Django 2.2 on 2020-07-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryapproval',
            name='action',
            field=models.TextField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], null=True),
        ),
    ]
