# Generated by Django 2.2 on 2020-07-03 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20200703_0016'),
        ('Approval', '0002_groceryapproval_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='FruitApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.TextField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], null=True)),
                ('fruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruit_fruit_approval_fruit', to='Shop.Fruit')),
            ],
            options={
                'verbose_name': 'Fruit Approval',
                'verbose_name_plural': 'Fruit Approvals',
            },
        ),
    ]
