# Generated by Django 2.2 on 2020-07-09 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0014_foodpackage_is_approved'),
        ('Approval', '0004_vegetableapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPackageApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.TextField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], null=True)),
                ('food_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_package_food_package_approval_food_package', to='Shop.FoodPackage')),
            ],
            options={
                'verbose_name': 'Food Package Approval',
                'verbose_name_plural': 'Food Package Approvals',
            },
        ),
    ]
