# Generated by Django 2.2 on 2020-07-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_auto_20200711_0935'),
        ('Approval', '0005_foodpackageapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMealApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.TextField(blank=True, choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], null=True)),
                ('meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_food_meal_meal', to='Shop.FoodMeal')),
            ],
            options={
                'verbose_name': 'Food Meal Approval',
                'verbose_name_plural': 'Food Meal Approvals',
            },
        ),
    ]
