# Generated by Django 2.2 on 2020-05-27 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_fooddishes_foodpackage_fruit_grocery_slots_vegetable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodpackage',
            options={'verbose_name': 'Food Package', 'verbose_name_plural': 'Food Packages'},
        ),
        migrations.AddField(
            model_name='fooddishes',
            name='number_of_items',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
