# Generated by Django 2.2 on 2020-05-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20200527_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddishes',
            name='food_type',
        ),
        migrations.AddField(
            model_name='foodpackage',
            name='food_type',
            field=models.TextField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], null=True),
        ),
    ]
