# Generated by Django 2.2 on 2020-05-29 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20200527_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='price_per_kg',
        ),
        migrations.AddField(
            model_name='shoppromocode',
            name='maximum_discount_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='shoppromocode',
            name='maximum_number_of_usage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='GroceryInNumOfItemsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('grocery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_grocery_items_grocery', to='Shop.Grocery')),
            ],
            options={
                'verbose_name': 'Grocery In Num Of ItemsPrice',
                'verbose_name_plural': 'Grocery In Num Of ItemsPrice',
            },
        ),
        migrations.CreateModel(
            name='GroceryInKgQuantityPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('grocery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_grocery_quantity_grocery', to='Shop.Grocery')),
            ],
            options={
                'verbose_name': 'Grocery Item Quantity Price',
                'verbose_name_plural': 'Grocery Item Quantity Price',
            },
        ),
    ]
