# Generated by Django 2.2 on 2020-07-02 12:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20200529_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryInLitresPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litre', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('grocery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_grocery_litres_grocery', to='Shop.Grocery')),
            ],
            options={
                'verbose_name': 'Grocery In Litres ItemsPrice',
                'verbose_name_plural': 'Grocery In Litres ItemsPrice',
            },
        ),
    ]
