# Generated by Django 2.2 on 2020-07-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_groceryinlitresprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groceryinlitresprice',
            options={'verbose_name': 'Grocery In Litre Price', 'verbose_name_plural': 'Grocery In Litre Price'},
        ),
    ]
