# Generated by Django 2.2 on 2020-07-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_grocery_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
