# Generated by Django 2.2 on 2020-07-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20200703_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='vegetable',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
