# Generated by Django 2.2 on 2020-07-09 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
        ('Shop', '0011_auto_20200709_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPackageClientSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_types', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_food_package_client_subscription_client', to='Client.Client')),
                ('food_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_food_package_client_subscription_food_subscription', to='Shop.FoodPackage')),
            ],
            options={
                'verbose_name': 'Food Package Client Subscription',
                'verbose_name_plural': 'Food Package Client Subscriptions',
            },
        ),
    ]
