# Generated by Django 2.2 on 2020-07-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_foodpackageclientsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodpackageclientsubscription',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodpackageclientsubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
