# Generated by Django 2.2 on 2020-07-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_shopfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
