# Generated by Django 2.2 on 2020-07-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_auto_20200710_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppromocode',
            name='category',
            field=models.TextField(blank=True, choices=[('Grocery', 'Grocery'), ('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Food', 'Food')], null=True),
        ),
    ]
