# Generated by Django 2.2 on 2020-07-11 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_shoppromocode_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmeal',
            name='package',
        ),
        migrations.AddField(
            model_name='foodmeal',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='foodmeal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodmeal',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='foodmeal',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_food_meal_shop', to='Shop.Shop'),
        ),
    ]
