# Generated by Django 2.2 on 2020-07-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0018_auto_20200711_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopfeedback',
            name='client',
        ),
        migrations.RemoveField(
            model_name='shopfeedback',
            name='shop',
        ),
        migrations.DeleteModel(
            name='FoodPackageClientSubscription',
        ),
        migrations.DeleteModel(
            name='ShopFeedBack',
        ),
    ]
