# Generated by Django 2.2 on 2020-07-28 23:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0019_auto_20200718_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_type', models.TextField(blank=True, choices=[('KG', 'KG'), ('Lts', 'Lts'), ('No', 'No')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('grocery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_grocery_price_grocery', to='Shop.Grocery')),
            ],
            options={
                'verbose_name': 'Grocery Price',
                'verbose_name_plural': 'Grocery Price',
            },
        ),
        migrations.RemoveField(
            model_name='groceryinlitresprice',
            name='grocery',
        ),
        migrations.RemoveField(
            model_name='groceryinnumofitemsprice',
            name='grocery',
        ),
        migrations.DeleteModel(
            name='GroceryInKgQuantityPrice',
        ),
        migrations.DeleteModel(
            name='GroceryInLitresPrice',
        ),
        migrations.DeleteModel(
            name='GroceryInNumOfItemsPrice',
        ),
    ]
