# Generated by Django 2.2 on 2020-08-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0020_auto_20200728_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmeal',
            name='is_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
