# Generated by Django 2.2 on 2020-08-07 02:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fruit', '0001_initial'),
        ('Food', '0001_initial'),
        ('Vegetable', '0001_initial'),
        ('Grocery', '0001_initial'),
        ('Shop', '0001_initial'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVegetableCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_vegetable_cart_client', to='Client.Client')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_vegetable_cart_shop', to='Shop.Shop')),
                ('vegetable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_vegetable_cart_vegetable', to='Vegetable.Vegetable')),
            ],
            options={
                'verbose_name': 'Client Vegetable Cart',
                'verbose_name_plural': 'Client Vegetable Carts',
            },
        ),
        migrations.CreateModel(
            name='ClientGroceryCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_grocery_cart_client', to='Client.Client')),
                ('grocery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_grocery_cart_grocery', to='Grocery.Grocery')),
                ('grocery_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_grocery_cart_grocery_price', to='Grocery.GroceryPrice')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_grocery_cart_shop', to='Shop.Shop')),
            ],
            options={
                'verbose_name': 'Client Grocery Cart',
                'verbose_name_plural': 'Client Grocery Carts',
            },
        ),
        migrations.CreateModel(
            name='ClientFruitCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_fruit_cart_client', to='Client.Client')),
                ('fruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_fruit_cart_fruit', to='Fruit.Fruit')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_fruit_cart_shop', to='Shop.Shop')),
            ],
            options={
                'verbose_name': 'Client Fruit Cart',
                'verbose_name_plural': 'Client Fruit Carts',
            },
        ),
        migrations.CreateModel(
            name='ClientFoodMealCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_food_meal_cart_client', to='Client.Client')),
                ('food_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_food_meal_cart_grocery', to='Food.FoodMeal')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_food_meal_cart_shop', to='Shop.Shop')),
            ],
            options={
                'verbose_name': 'Client Food Meal Cart',
                'verbose_name_plural': 'Client Food Meal Carts',
            },
        ),
    ]
