# Generated by Django 2.2 on 2020-08-15 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fruit', '0001_initial'),
        ('Vegetable', '0002_auto_20200809_0911'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfruitcart',
            name='fruit_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_fruit_cart_fruit_price', to='Fruit.FruitPrice'),
        ),
        migrations.AddField(
            model_name='clientvegetablecart',
            name='vegetable_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_vegetable_cart_vegetable_price', to='Vegetable.VegetablePrice'),
        ),
    ]
