# Generated by Django 2.2 on 2020-09-11 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20200807_0241'),
        ('Shop', '0002_auto_20200807_0244'),
        ('FoodPackage', '0002_auto_20200809_1136'),
        ('Cart', '0002_auto_20200815_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFoodPackageCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_food_package_cart_client', to='Client.Client')),
                ('food_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_food_package_cart_food_package', to='FoodPackage.FoodPackage')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_client_food_package_cart_shop', to='Shop.Shop')),
            ],
            options={
                'verbose_name': 'Client Food Package Cart',
                'verbose_name_plural': 'Client Food Package Carts',
            },
        ),
    ]
