# Generated by Django 2.2 on 2020-10-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_auth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNumberOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('otp', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Mobile Number OTP',
                'verbose_name_plural': 'Mobile Number OTPs',
            },
        ),
    ]
