# Generated by Django 2.2 on 2020-08-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooddishes',
            options={'verbose_name': 'Food Dish', 'verbose_name_plural': 'Food Dishes'},
        ),
    ]
