# Generated by Django 2.2 on 2020-08-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_auto_20200809_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodmeal',
            name='day',
        ),
    ]
