# Generated by Django 2.2 on 2020-08-24 06:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fruit', '0001_initial'),
        ('Food', '0002_auto_20200809_0911'),
        ('Shop', '0002_auto_20200807_0244'),
        ('Client', '0002_auto_20200807_0241'),
        ('Grocery', '0001_initial'),
        ('Vegetable', '0003_remove_vegetable_price_per_kg'),
        ('Promocode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.TextField(blank=True, choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online Payment', 'Online Payment')], null=True)),
                ('is_delivered', models.BooleanField(blank=True, default=False, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_type', models.TextField(blank=True, choices=[('Food', 'Food'), ('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Grocery', 'Grocery')], null=True)),
                ('status', models.TextField(blank=True, choices=[('packaging', 'packaging'), ('on_way', 'on_way'), ('delivered', 'delivered')], null=True)),
                ('client_address_details', models.TextField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_client', to='Client.Client')),
                ('promocode_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_promocode_used', to='Promocode.ShopPromocode')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_shop', to='Shop.Shop')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_order_slot', to='Shop.Slots')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderVegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_vegetable_order', to='Order.Order')),
                ('vegetable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_vegetable_vegetable', to='Vegetable.Vegetable')),
                ('vegetable_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_vegetable_vegetable_price', to='Vegetable.VegetablePrice')),
            ],
            options={
                'verbose_name': 'Order Vegetable',
                'verbose_name_plural': 'Order Vegetables',
            },
        ),
        migrations.CreateModel(
            name='OrderGrocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('grocery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_grocery_grocery', to='Grocery.Grocery')),
                ('grocery_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_grocery_grocery_price', to='Grocery.GroceryPrice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_grocery_order', to='Order.Order')),
            ],
            options={
                'verbose_name': 'Order Grocery',
                'verbose_name_plural': 'Order Groceries',
            },
        ),
        migrations.CreateModel(
            name='OrderFruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fruit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_fruit_fruit', to='Fruit.Fruit')),
                ('fruit_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_fruit_fruit_price', to='Fruit.FruitPrice')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_fruit_order', to='Order.Order')),
            ],
            options={
                'verbose_name': 'Order Fruit',
                'verbose_name_plural': 'Order Fruites',
            },
        ),
        migrations.CreateModel(
            name='OrderFoodMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_items', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('food_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_food_meal_food_meal', to='Food.FoodMeal')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_order_food_meal_order', to='Order.Order')),
            ],
            options={
                'verbose_name': 'Order FoodMeal',
                'verbose_name_plural': 'Order FoodMeals',
            },
        ),
        migrations.CreateModel(
            name='OnGoingOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_ongoing_order_order', to='Order.Order')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_ongoing_order_shop', to='Shop.Shop')),
            ],
            options={
                'verbose_name': 'Ongoing Order',
                'verbose_name_plural': 'Ongoing Orders',
            },
        ),
    ]
