# Generated by Django 2.2 on 2020-09-12 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_foodmeal_day'),
        ('FoodPackage', '0003_foodpackage_food_type'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.TextField(blank=True, choices=[('Food', 'Food'), ('Fruit', 'Fruit'), ('Vegetable', 'Vegetable'), ('Grocery', 'Grocery'), ('FoodPackage', 'FoodPackage')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, choices=[('packaging', 'packaging'), ('on_way', 'on_way'), ('delivered', 'delivered'), ('food_package', 'food_package')], null=True),
        ),
        migrations.CreateModel(
            name='FoodPackageEachMealOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, choices=[('packaging', 'packaging'), ('on_way', 'on_way'), ('delivered', 'delivered'), ('food_package', 'food_package')], null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('food_meal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_food_package_meal_order_food_meal', to='Food.FoodMeal')),
                ('food_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_food_package_meal_order_food_package', to='FoodPackage.FoodPackage')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_food_package_meal_order_order', to='Order.Order')),
            ],
            options={
                'verbose_name': 'Food Package Each Meal Order',
                'verbose_name_plural': 'Food Package Each Meal Orders',
            },
        ),
    ]
