# Generated by Django 2.2 on 2020-09-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20200912_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpackageeachmealorder',
            name='status',
            field=models.TextField(blank=True, choices=[('upcoming', 'upcoming'), ('packaging', 'packaging'), ('on_way', 'on_way'), ('delivered', 'delivered'), ('food_package', 'food_package')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(blank=True, choices=[('upcoming', 'upcoming'), ('packaging', 'packaging'), ('on_way', 'on_way'), ('delivered', 'delivered'), ('food_package', 'food_package')], null=True),
        ),
    ]
