# Generated by Django 2.2 on 2020-10-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20200930_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingorders',
            name='created',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
